server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: bookingMicroservice
          uri: http://localhost:8081/
          predicates:
            - Path=/hotel/**

        - id: paymentMicroservice
          uri: http://localhost:8083/
          predicates:
            - Path=/payment/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/